object Form5: TForm5
  Left = 0
  Top = 0
  Caption = 'Form5'
  ClientHeight = 261
  ClientWidth = 484
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object PanelMain: TPanel
    Left = 0
    Top = 0
    Width = 484
    Height = 261
    Align = alClient
    Caption = 'PanelMain'
    Color = clWhite
    ParentBackground = False
    ShowCaption = False
    TabOrder = 0
    ExplicitWidth = 534
    ExplicitHeight = 450
    object PanelTitleView: TPanel
      Left = 1
      Top = 1
      Width = 482
      Height = 64
      Align = alTop
      Caption = 'Change View'
      Color = clHoneydew
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
    end
    object PanelChooseAll: TPanel
      Left = 1
      Top = 65
      Width = 482
      Height = 71
      Align = alTop
      BevelOuter = bvNone
      Caption = 'PanelChooseAll'
      Color = clWhite
      ParentBackground = False
      ShowCaption = False
      TabOrder = 1
      ExplicitTop = 195
      object ButtonChooseAll: TButton
        AlignWithMargins = True
        Left = 30
        Top = 20
        Width = 161
        Height = 31
        Margins.Left = 30
        Margins.Top = 20
        Margins.Right = 30
        Margins.Bottom = 20
        Align = alLeft
        Caption = 'Choose all days'
        TabOrder = 0
        OnClick = ButtonChooseAllClick
        ExplicitLeft = 0
        ExplicitTop = 0
        ExplicitHeight = 71
      end
      object ButtonCheckWeekdays: TButton
        AlignWithMargins = True
        Left = 291
        Top = 20
        Width = 161
        Height = 31
        Margins.Left = 30
        Margins.Top = 20
        Margins.Right = 30
        Margins.Bottom = 20
        Align = alRight
        Caption = 'Choose weekdays'
        TabOrder = 1
        OnClick = ButtonCheckWeekdaysClick
        ExplicitLeft = 332
      end
    end
    object PanelChooseDays: TPanel
      AlignWithMargins = True
      Left = 4
      Top = 146
      Width = 476
      Height = 43
      Margins.Top = 10
      Margins.Bottom = 0
      Align = alClient
      BevelOuter = bvNone
      Caption = 'PanelChooseDays'
      Color = clWhite
      ParentBackground = False
      ShowCaption = False
      TabOrder = 2
      ExplicitLeft = 192
      ExplicitTop = 184
      ExplicitWidth = 185
      ExplicitHeight = 41
      object PanelCheckMonday: TPanel
        Left = 0
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        Color = clWhite
        ParentBackground = False
        ShowCaption = False
        TabOrder = 0
        ExplicitHeight = 139
        object LabelCheckMonday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Monday'
          ExplicitWidth = 44
        end
        object CheckBoxMonday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          Color = clWhite
          ParentColor = False
          TabOrder = 0
          ExplicitLeft = 0
          ExplicitTop = 15
          ExplicitWidth = 68
        end
      end
      object PanelCheckTuesday: TPanel
        Left = 68
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        ParentColor = True
        ShowCaption = False
        TabOrder = 1
        ExplicitLeft = 128
        ExplicitTop = 6
        ExplicitHeight = 139
        object LabelCheckTuesday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Tuesday'
          ExplicitWidth = 44
        end
        object CheckBoxTuesday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          TabOrder = 0
        end
      end
      object PanelCheckWednesday: TPanel
        Left = 136
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        ParentColor = True
        ShowCaption = False
        TabOrder = 2
        ExplicitLeft = 236
        ExplicitHeight = 139
        object LabelCheckWednesday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Wednesday'
          ExplicitWidth = 61
        end
        object CheckBoxWednesday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          TabOrder = 0
        end
      end
      object PanelCheckThursday: TPanel
        Left = 204
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        ParentColor = True
        ShowCaption = False
        TabOrder = 3
        ExplicitLeft = 278
        ExplicitHeight = 139
        object LabelCheckThursday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Thursday'
          ExplicitWidth = 49
        end
        object CheckBoxThursday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          TabOrder = 0
        end
      end
      object PanelCheckFriday: TPanel
        Left = 272
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        ParentColor = True
        ShowCaption = False
        TabOrder = 4
        ExplicitLeft = 364
        ExplicitTop = 6
        ExplicitHeight = 139
        object LabelCheckFriday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Friday'
          ExplicitWidth = 32
        end
        object CheckBoxFriday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          TabOrder = 0
        end
      end
      object PanelCheckSaturday: TPanel
        Left = 340
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        ParentColor = True
        ShowCaption = False
        TabOrder = 5
        ExplicitLeft = 396
        ExplicitHeight = 139
        object LabelCheckSaturday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Saturday'
          ExplicitWidth = 46
        end
        object CheckBoxSaturday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          TabOrder = 0
        end
      end
      object PanelCheckSunday: TPanel
        Left = 408
        Top = 0
        Width = 68
        Height = 43
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'PanelCheckMonday'
        ParentColor = True
        ShowCaption = False
        TabOrder = 6
        ExplicitLeft = 411
        ExplicitHeight = 139
        object LabelCheckSunday: TLabel
          Left = 0
          Top = 0
          Width = 68
          Height = 15
          Align = alTop
          Alignment = taCenter
          Caption = 'Sunday'
          ExplicitWidth = 39
        end
        object CheckBoxSunday: TCheckBox
          AlignWithMargins = True
          Left = 25
          Top = 18
          Width = 40
          Height = 26
          Margins.Left = 25
          Align = alTop
          TabOrder = 0
        end
      end
    end
    object PanelCheckSave: TPanel
      Left = 1
      Top = 189
      Width = 482
      Height = 71
      Align = alBottom
      BevelOuter = bvNone
      Caption = 'PanelChooseAll'
      Color = clWhite
      ParentBackground = False
      ShowCaption = False
      TabOrder = 3
      ExplicitTop = 50
      object ButtonCheckSave: TButton
        AlignWithMargins = True
        Left = 343
        Top = 20
        Width = 119
        Height = 31
        Margins.Left = 20
        Margins.Top = 20
        Margins.Right = 20
        Margins.Bottom = 20
        Align = alRight
        Caption = 'Save changes'
        TabOrder = 0
        OnClick = ButtonCheckSaveClick
      end
    end
  end
end
